name: Cypress Cross-Browser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node modules and Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ matrix.browser }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.browser }}

      - name: Install dependencies
        run: npm install

      - name: Set executable permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Install Cypress binary
        run: npx cypress install

      - name: Verify Cypress binary installation
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}
