name: Cypress Cross-Browser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Cache Node modules and Cypress binary
      - name: Cache Node modules and Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ matrix.browser }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.browser }}

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Install Cypress binary
      - name: Install Cypress
        run: npm install cypress --save-dev

      # Step 6: Set Cypress binary permissions
      - name: Set executable permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress

      # Step 7: Verify the Cypress binary installation
      - name: Verify Cypress binary installation
        run: npx cypress verify

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}
