name: Cypress Cross-Browser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    # Run on the latest available Ubuntu runner
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set a timeout of 60 minutes for the job

    strategy:
      matrix:
        # Define browsers for cross-browser testing
        browser: [chrome, firefox, edge]

    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set executable permissions for Cypress binary
      - name: Set executable permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress

      # Step 5: Verify the Cypress binary installation
      - name: Verify Cypress binary installation
        run: npx cypress verify

      # Step 6: Run Cypress tests across different browsers
      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}

